### ISSUE TITLE
Consider not running migrate.sh as part of go.sh

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#133]
There are many reasons why you might want to start working on a project but not run the migrations:

* Still in the middle of writing/testing migrations
* Migrations didn't apply cleanly and you need to activate the project to find out
* You have a different branch checked out (and thus a different database enabled) than the one which you intend to run migrations on
* To save time

I find myself regularly commenting out the migrate line.

**Comment by mrmachine** [comment]
@cogat that's why it's only a default, and easy to override (without commenting out any lines in any files).

https://github.com/ic-labs/django-icekit/blob/eb11c1ed41327b002e593decaada5b9dd6edb9be/project_template/go.sh#L35

Just pass the command you actually want to run inside the entrypoint context as an argument to go.sh, just like you would to docker-compose. e.g. `go.sh bash.sh` (to bypass `setup-django.sh`) and then interactively debug or do whatever you need to do.

If a change is needed here, it might be to add some stdout to `entrypoint.sh` which says (when no command is explicitly provided) "Executing the default `setup-django.sh bash.sh` command. To execute something else, pass a different command as arguments. For example, `docker-compose run --rm --service-ports django bash.sh` or `go.sh bash.sh`"

**Comment by cogat** [comment]
Thanks for the explanation. I would suggest that if running `go.sh` with no parameters gets you a shell by default, then maybe a safe/intuitive behaviour should be substantially the same as `go.sh bash.sh`, maybe warning that things are out of date, and maybe a documented `go.sh update-django.sh` would update. My 2c.

**Comment by mrmachine** [comment]
Generally, migrations should work. You create them and test them in a running shell and they are tested on Travis CI (if not already baked into the test initial database). `setup-django.sh` does more than just apply migrations. It is essential to run (at least once) before the project can run, and ideally it should be run not only when the developer knows that something (again, more than just migrations) is out of date. It's already very easy to forget that you need to apply migrations, especially if switching branches and DBs locally. I think the default behaviour of automatically applying outdated migrations and installing outdated/missing bower/python requirements to ensure the environment matches the project is the right default. It only happens automatically one time per session/terminal, when you drop into a container or go.sh shell. If it breaks, it is easy to bypass.
