### ISSUE TITLE
Publish view not working on ACMI article?

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#152]
1) Publish an article
2) Visit the URL for the article
3) You are redirected to the preview URL.

**Comment by cogat** [comment]
The fix should also be applied upstream to glamkit articles, of which this is a portable copy, and potentially other kinds of collected content.

**Comment by jmurty** [comment]
My suspicion is that this seeming bug is caused by the Article Listing page not being published.

This listing page is suppose to be the root page for articles and it must exist and be published for the public to view any individual published article. If the listing page exists but is not published, privileged users will get redirected to a preview URL so they can see the draft listing page, but the general public will just get a 404.
