### ISSUE TITLE
Convert documentation to ReStructured Text

### ISSUE THREAD

**Issue by cogat** [ic-labs/django-icekit#188]

**Comment by cogat** [comment]
@andrewserong while I'm doing this is there anything you want me to document?

**Comment by andrewserong** [comment]
Hi @cogat -- welcome back!

The main things for us now are:

* Deployment instructions (Tai mentioned SFMOMA had some), with a bit of detail surrounding updating the changelog and the overall deployment workflow. Basically so that when we are doing deployments, we're doing them in a way that's consistent with your workflows and standards and makes it straightforward for us all working in a shared repo.
* Rolling back an unsuccessful deployment on Production. (Is it just deploy a fix to Production, wait for a successful build in Travis, then redeploy the containers in Docker cloud?) -- is there a quicker way?
* How to rebuild the elasticsearch indexes?
* How to set up a task on Staging and Production, and what to do if you need to switch it off (or it fails)?
* How to create new nodes in Production if the existing nodes fail (is this in AWS or Docker cloud, or both?) -- basically just going over the fix for the issue the other day.

And it's totally fine if some of these are simple dot points with links to docs on Docker or AWS. I still have much to learn when it comes to AWS!

**Comment by melrumble** [comment]
This is similar to #315

**Comment by andrewserong** [comment]
Hi @cogat -- just another one for this:

Are you able to expand on the instructions here: https://github.com/ic-labs/django-icekit/blob/develop/docs/intro/docker.md to include step-by-step instructions on connecting to the cloud container, and hooking up a development environment to the dumped database? If it's more appropriate to be in the Icekit repo documentation, then more generally it would be "setting up a local environment to match an existing project hosted in Docker Cloud".

**Comment by cogat** [comment]
@andrewserong latest commit on the docs-refactor branch contains the documentation you requested, except `How to create new nodes in Production if the existing nodes fail` - I can't remember the issue you're referring to. If the existing nodes fail, one normally restarts or redeploys using Docker cloud, which I've made reference to in the documentation on fixing a broken deployment.
