### ISSUE TITLE
Stuck during docker-compose run, waiting to acquire lock for command: setup-postgres.sh

### ISSUE THREAD

**Issue by pvperez1** [ic-labs/django-icekit#312]
Help please, I have never used docker and it seems that I am getting an error with postgres. This is what is listed in the logs:

```
Error: Database is uninitialized and superuser password is not specified.
You must specify POSTGRES_PASSWORD for the superuser. Use
"-e POSTGRES_PASSWORD=password" to set it in "docker run".

You may also use POSTGRES_HOST_AUTH_METHOD=trust to allow all connections
without a password. This is *not* recommended. See PostgreSQL
documentation about "trust":
https://www.postgresql.org/docs/current/auth-trust.html
```

Any recommendations on how I should go about this? WIll really appreciate it, thanks!

**Comment by jmurty** [comment]
Hi @pvperez1 please be aware that this project is defunct, see https://interaction.net.au/articles/glamkit-dead-long-live-glamkit/

Since it is no longer maintained or developed I wouldn't encourage you to spend time on it.

But for your specific question, for a while now PostgreSQL Docker images have required an extra environment variable to be set to permit access without passwords. Add an `environment` section to the `postgres` service definition in *docker-compose.yml* like this:
```yaml
  postgres:
    . . .
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
   . . .
```

**Comment by pvperez1** [comment]
Aww, sorry to hear about that. But thanks for informing me. Will try Wagtail insteaad
